### ISSUE TITLE
Unable to delete names of old players from the list

### ISSUE THREAD

**Issue by silentSquid** [MrCrayfish/MightyMail#18]
Hi there!

On a 1.20.1 Fabric server we have a bunch of old names in the list that we're unable to delete. The chunks where their mailboxes were have been reset and those boxes dont physically exist anymore but people's names are still in the list with black icons and "unknown player" tooltip when hovered over.
I've tried removing the mod, restarting the server, joining in then readding the mod back and restarting again... names were still in the list.
Here's a pic:
![image](https://github.com/MrCrayfish/MightyMail/assets/3385529/13b93785-6b14-4588-b8eb-d4c313493ccd)

Is there any way to remove those names? Are they stored somewhere? I couldnt find anything about that in configs. 
I can provide more info if needed.
Thanks in advance!

**Comment by MrCrayfish** [comment]
I will look into checking for invalid mailboxes and removing them. Thanks for bringing this up.

If you really want to resolve the issue before the fix, in your world save, locate `data/refurbished_furniture_delivery_service.dat` and open with this website: https://irath96.github.io/webNBT/ You can then delete the invalid mailboxes.

**Comment by silentSquid** [comment]
Thanks so much! I'll dig in there!
