### ISSUE TITLE
[Forge 1.19.2] You can bypass the "no cointainers" rule by using a hopper on the postbox (Also works for backpacked)

### ISSUE THREAD

**Issue by Looxond** [MrCrayfish/MightyMail#2]
Heres the vid

https://youtu.be/1QfFTfgRX2Q

**Comment by Looxond** [comment]
Forgot to add the backpacked part

https://github.com/MrCrayfish/MightyMail/assets/29359853/84d293c5-c545-43ac-a3d5-99d1498e9c0a

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MightyMail/commit/2c490472162ff9b5901741904e1807152fff892a for Mighty Mail. Will do Backpacked next.
