### ISSUE TITLE
Strange crash/freeze on the lastest version (forge 1.20.1)

### ISSUE THREAD

**Issue by Looxond** [MrCrayfish/MightyMail#23]
https://mclo.gs/GaWUFqd

**Comment by DrakonFG** [comment]
Here too
[crash-2024-09-13_16.42.31-server.txt](https://github.com/user-attachments/files/16996450/crash-2024-09-13_16.42.31-server.txt)

**Comment by vinnyg0621** [comment]
same problem

**Comment by Looxond** [comment]
Im bad at reading logs but im going to assume its related to the latest changes made to be compatible with MrCrayfish's Furniture Mod: Refurbished

**Comment by DrakonFG** [comment]
Yes, the last update crashed the game, yes, for me was when server was starting, I sent the log in order to try help you to find the error. Mine Version 1.20,1 Forge is 47.3.X

**Comment by vinnyg0621** [comment]
> Yes, the last update crashed the game, yes, for me was when server was starting, I sent the log in order to try help you to find the error. Mine Version 1.20,1 Forge is 47.3.X

same

**Comment by Looxond** [comment]
I followed what the update told me to do, i changed the name of the file in saves/world/data and still crashed

**Comment by Looxond** [comment]
That funny moment when mighty mail has RMF for some reason dependency
![image](https://github.com/user-attachments/assets/7cc78555-10e9-453a-bb94-5aac3ac4edec)
![image](https://github.com/user-attachments/assets/9c1702ab-109e-4a8b-8121-2ff61599f6cd)

**Comment by MrCrayfish** [comment]
It's not a dependency. The latest update includes a new command that you can run to migrate the mailboxes from Mighty Mail to Refurbished Furniture. It was a error on my part that caused it to try loading classes without them existing.

**Comment by Looxond** [comment]
This has been fixed in the latest version. Now i can spam my friends with junk mail again, ty for the update!
