### ISSUE TITLE
Sound Subtlitle Not Working

### ISSUE THREAD

**Issue by DEMnetwork** [MrCrayfish/MightyMail#5]
Minecraft Version: 1.19,4
Modlaoder: Quilt
Mod version:  1.0.13
Image: 
https://media.essential.gg/88446f9f-582b-4d5b-daa5-d3aa2b329600

**Comment by MrCrayfish** [comment]
Thanks. Fixed in 309227e35739d91a05a09aab48d216f5a47ba7d5
