### ISSUE TITLE
Mailboxes loses their name after reboot

### ISSUE THREAD

**Issue by Hypario** [MrCrayfish/MightyMail#6]
Hello ! 

I only tried on singleplayer for a few tests, but the names of the mailboxes disappear after a world restart.

basically, just place down a mailbox, give it a name, leave the world and join back, and the name will disappear.

I am guessing the behavior is the same on a server restart (as that can happen frequently to free some ram), I'm gonna try later today.

**Comment by MrCrayfish** [comment]
What version are you using?

**Comment by Hypario** [comment]
I'm using the last version available on curseforge, on minecraft 1.19.2

**Comment by MrCrayfish** [comment]
And what version is that?

**Comment by MrCrayfish** [comment]
Just to clarify, you are pressing "Accept" when you name your mailbox?

**Comment by Hypario** [comment]
mod version 1.0.13, and yes I am pressing "Accept" when I name my mailbox, I can record it for you if needed

**Comment by Hypario** [comment]
I recorded the behavior, it should be available on https://youtu.be/Z3l1fZth2c0

**Comment by MrCrayfish** [comment]
I've located the issue. It was due to the character `:` being present in the file name, which is an illegal character for file names. What is strange is that I didn't run into the problem, even with all the restarts and tests I've done. I'll have a patch out soon.

**Comment by MrCrayfish** [comment]
Fixed in 1.0.14
