### ISSUE TITLE
[Request] Notification of mail

### ISSUE THREAD

**Issue by CreativeManul** [MrCrayfish/MightyMail#7]
I and my users frequently forget to check our mailboxes.

Maybe you can add something for notification? It’s better to show that the box is not empty.

A system similar to what [Contact](https://www.curseforge.com/minecraft/mc-mods/contact) does, where you receive a chat notification if you're online when you receive mail. Additionally, the snailbox could have a visual indicator when it has mail (in case it arrives when you're offline).

Although, perhaps I have some problems because I don’t see the red flag.

**Comment by MrCrayfish** [comment]
The red flag shows when a package is added to your mailbox. It is removed when any player opens your mailbox.

Just want to confirm you are using Mighty Mail, and not the mailing system from the current released version of the Furniture Mod as that doesn't have the red flag.

**Comment by CreativeManul** [comment]
Yes, I saw the flag! There was a problem with some kind of conflict, after clearing the mods everything was fine, flat textures were not displayed correctly! Thank you very much for your wonderful mod)
