### ISSUE TITLE
sending multiple pakages dosnt always arive and dissapear.

### ISSUE THREAD

**Issue by GreenForzeGaming** [MrCrayfish/MightyMail#8]
we didnt need to have the mod too be way too realistic.
idk what causes thyis but something makes it so some pakages sent to a mailbox in succesion causes the newest pakage too dissapear
![Mod list 1](https://github.com/MrCrayfish/MightyMail/assets/62345403/4f537f83-11b8-44e7-a937-f3695dac2df1)
![Mod list 2](https://github.com/MrCrayfish/MightyMail/assets/62345403/e116d3d7-a1bc-4559-90be-df7ef88640fc)
![Mod list 3](https://github.com/MrCrayfish/MightyMail/assets/62345403/b235555a-b445-4c32-89d1-5d1b016ee86e)
im using the latest stable version of this mod
with forge 47.2.0
and the 3 pictures above are the mods i have combined.

**Comment by MrCrayfish** [comment]
You're gonna have to contact your mail courier on that one.

On topic, what do you mean sending multiple packages, as the mod only allows sending one at a time?
Can you also please send your game log, there is potentially an error printed into the log.

**Comment by GreenForzeGaming** [comment]
if i send 2 pakages at once from the gui 1 after the other. there has been issues when the reciver isnt online . they then only get one of the pakages and the other one dissapears. once a item also returned too me from the box as if it was never sent. i do not have a log of that particular day

**Comment by MrCrayfish** [comment]
I've looked into the code and may have potentially found an issue where items queued for delivery aren't saved. This could explain the second package not being sent. As for the items returning to you, that's not a feature. Are you sure you didn't just break a post box with items inside? No code in the mod send the items to a player, only mailboxes.

**Comment by MrCrayfish** [comment]
I've merged a fix (https://github.com/MrCrayfish/MightyMail/commit/d3e2d098bc9d3a0557986626cf7028af2fe42e6a) that should fix an issue where the mailing queue wasn't saved. As mentioned before, that might explain why the package went missing. Release will be out soon
